export const endpoints = {
    Graph: 'Graph/All',
    GraphType: 'Graph/Types',
    GraphSave: 'Graph/Save',
    GraphDelete: 'Graph',
    graphById: 'Graph',
    getAllDataSource: 'data/Sources',
    getColumns: 'data/Properties',
    getGraphData: 'data/ForGraph',
    all: 'data/ForTable',
    GetMatricOperationValue: 'Data/GetMatricOperationValue',
    dataAsCsv: 'data/AsCsvFile',
    dashboardSave: 'dashboard',
    dashboardUpdateSortOrder: 'dashboard/UpdateSortOrder',
    GetDashboard: 'dashboard',
    GetDashboardById: 'dashboard',
    deleteDashboard: 'dashboard',
    getAllDataMerge: 'DataMerge',
    saveDataMerge: 'DataMerge/Save',
    deleteDataMerge: 'DataMerge/MergeQuery',
    validateUser: 'user/validate',
    logout: 'user/logout',
}